services:
  - type: web
    name: mtgv-web
    env: static
    buildCommand: npm run build:static
    staticPublishPath: ./out
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
